<a href="https://colab.research.google.com/github/GezhinOleg/Num_Pnd_L1/blob/main/numpy_L1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Задание 1
Создайте numpy array с элементами от числа N до 0
(например, для N = 10 это будет
array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [2]:
# Два варианта, первый придумал сам, второй подсмотрел в сети.
num = int(input())
arr = np.arange(-num, 1) * -1
print(arr)
# ------------------------
arr2 = np.arange(num + 1)
arr2 = arr2[::-1]
print(arr2)

5
[5 4 3 2 1 0]
[5 4 3 2 1 0]


Задание 2
Создайте диагональную матрицу с элементами от N до 0.
Посчитайте сумму ее значений на диагонали.

In [3]:
num = int(input())
arr3 = np.diag(np.arange(-num, 1) * -1, k=0)
print(arr3)
print('Diagonal (sum): ', np.trace(arr3))
print('Diagonal (elements): ', np.diagonal(arr3))

10
[[10  0  0  0  0  0  0  0  0  0  0]
 [ 0  9  0  0  0  0  0  0  0  0  0]
 [ 0  0  8  0  0  0  0  0  0  0  0]
 [ 0  0  0  7  0  0  0  0  0  0  0]
 [ 0  0  0  0  6  0  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  0  4  0  0  0  0]
 [ 0  0  0  0  0  0  0  3  0  0  0]
 [ 0  0  0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]]
Diagonal (sum):  55
Diagonal (elements):  [10  9  8  7  6  5  4  3  2  1  0]


Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [4]:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])
x = np.linalg.solve(a, b)

print(x)

[ 0.46666667  3.84444444 -5.55555556]


Имеется матрица покупок в интернет-магазине.
Столбец А - ID пользователя. Остальные
столбцы - количество покупок категорий
товаров этим пользователем:

In [10]:
def return_a():
    a = np.array([0, 1, 2, 0, 0, 0])
    aLength = np.linalg.norm(a)
    return aLength

In [11]:
def cosine(a, b, aLength):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    # длины векторов
    bLength = np.linalg.norm(b)
    return np.dot(a, b) / (aLength * bLength)

In [12]:
def calculation():
    '''
    В цикле перебираем векторы и тот, который имеет минимальное значение
    косинуса выводится в виде результата
    '''
    aLength = return_a()
    users_stats = np.array(
        [
            [2, 1, 0, 0, 0, 0],
            [1, 1, 2, 1, 0, 0],
            [2, 0, 1, 0, 0, 0],
            [1, 1, 2, 1, 0, 1],
            [0, 0, 1, 2, 0, 0],
            [0, 0, 0, 0, 0, 5],
            [1, 0, 0, 0, 0, 0],
            [0, 1, 1, 0, 0, 0],
            [0, 0, 0, 1, 1, 3],
            [1, 0, 0, 2, 1, 4]
        ],
        np.int32
    )
    a = np.array([0, 1, 2, 0, 0, 0])
    cos_max = 0
    nearest_vector = a
    for i in users_stats:
        b = i
        result = cosine(a, b, aLength)
        if result > cos_max:
            cos_max = result
            nearest_vector = b
    return nearest_vector


In [14]:
if __name__ == '__main__':
    print('Самый похожй пользователь: ', calculation())

Самый похожй пользователь:  [0 1 1 0 0 0]
